name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: helloWorldTest
      id: helloworldtest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: helloWorldTest
        setup-command: ''
        command: gradle test --tests LibraryTest.testHelloWorld
        timeout: 1
        max-score: 5
    - name: zebrackTest
      id: zebracktest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: zebrackTest
        setup-command: ''
        command: gradle test --tests LibraryTest.testHelloZebrack
        timeout: 1
        max-score: 15
    - name: genericTest
      id: generictest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: genericTest
        setup-command: ''
        command: gradle test
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLOWORLDTEST_RESULTS: "${{steps.helloworldtest.outputs.result}}"
        ZEBRACKTEST_RESULTS: "${{steps.zebracktest.outputs.result}}"
        GENERICTEST_RESULTS: "${{steps.generictest.outputs.result}}"
      with:
        runners: helloworldtest,zebracktest,generictest
